[www]
user = www-data
group = www-data

# --- INICIO DE LA CORRECCIÓN 502 ---
# Escucha en el nuevo socket en /var/run/php/
listen = /var/run/php/php-fpm.sock
# --- FIN DE LA CORRECCIÓN 502 ---

listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

clear_env = no
